"""Add descripcion and activo to Categoria

Revision ID: 26f092a78983
Revises: db46799b8c05
Create Date: 2026-09-17 12:10:10.602932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f092a78983'
down_revision: Union[str, Sequence[str], None] = 'db46799b8c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('categorias', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'activo')
    op.drop_column('categorias', 'descripcion')
    # ### end Alembic commands ###
