"""Add tipo_solicitud and requiere_delivery

Revision ID: 6c894ce26b8e
Revises: 26f092a78983
Create Date: 2026-09-17 18:16:01.005437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c894ce26b8e'
"""Add tipo_solicitud and requiere_delivery

Revision ID: 6c894ce26b8e
Revises: 26f092a78983
Create Date: 2026-09-17 18:16:01.005437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c894ce26b8e'
down_revision: Union[str, Sequence[str], None] = '26f092a78983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devoluciones', sa.Column('tipo_solicitud', sa.String(length=50), nullable=False, server_default='Devolución'))
    op.add_column('devoluciones', sa.Column('requiere_delivery', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devoluciones', 'requiere_delivery')
    op.drop_column('devoluciones', 'tipo_solicitud')
    # ### end Alembic commands ###
