"""add_devoluciones_delivery

Revision ID: 87519f1d0902
Revises: 2db956f448fa
Create Date: 2026-09-15 10:57:40.755743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87519f1d0902'
down_revision: Union[str, Sequence[str], None] = '2db956f448fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoluciones_id'), 'devoluciones', ['id'], unique=False)
    op.create_table('servicio_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('repartidor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones.id'], ),
    sa.ForeignKeyConstraint(['repartidor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicio_delivery_id'), 'servicio_delivery', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicio_delivery_id'), table_name='servicio_delivery')
    op.drop_table('servicio_delivery')
    op.drop_index(op.f('ix_devoluciones_id'), table_name='devoluciones')
    op.drop_table('devoluciones')
    # ### end Alembic commands ###
