"""Add modelo_3d_url to Productos

Revision ID: d49555a79be5
Revises: 9c215a7087b6
Create Date: 2026-09-03 19:14:03.165376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49555a79be5'
down_revision: Union[str, Sequence[str], None] = '9c215a7087b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('modelo_3d_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'modelo_3d_url')
    # ### end Alembic commands ###
