"""Add payment methods to Venta

Revision ID: db46799b8c05
Revises: 87519f1d0902
Create Date: 2026-09-17 11:38:06.851283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db46799b8c05'
down_revision: Union[str, Sequence[str], None] = '87519f1d0902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('metodo_pago', sa.String(length=50), nullable=True))
    op.add_column('ventas', sa.Column('transaccion_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'transaccion_id')
    op.drop_column('ventas', 'metodo_pago')
    # ### end Alembic commands ###
